"""change_user_id_to_integer

Revision ID: bf50882f547e
Revises: c04d6de36b2c
Create Date: 2025-04-25 10:43:25.371859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf50882f547e'
down_revision: Union[str, None] = 'c04d6de36b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE files ALTER COLUMN user_id TYPE INTEGER USING user_id::integer')
    op.execute('ALTER TABLE flashcards ALTER COLUMN user_id TYPE INTEGER USING user_id::integer')
    op.execute('ALTER TABLE study_folders ALTER COLUMN user_id TYPE INTEGER USING user_id::integer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_folders', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('flashcards', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('files', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
